version: '3.8'
services:
  app:
    build: .
    container_name: lmda
    ports:
      - '5001:5001'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/dbname
  db:
    image: 'postgres:13-alpine'
    container_name: lmda-postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lmda
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
volumes:
  pgdata:
